from . import res_config
from . import mob_synchronization
from . import account_payment
from . import attribute_sync
from . import bridge_backbone
from . import category_sync
from . import delivery_carrier
from . import product
from . import product_attribute
from . import product_sync
from . import product_template
from . import magento_attribute_set
from . import magento_category
from . import magento_configure
from . import magento_customer
from . import magento_product
from . import magento_product_attribute
from . import magento_product_attribute_value
from . import magento_product_template
from . import magento_region
from . import magento_store
from . import magento_store_view
from . import magento_sync_history
from . import magento_website
from . import res_partner
from . import sale
from . import stock_picking
from . import wk_skeleton
from . import dashboard_extend
from . import res_company

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
